name: Cut Release

on:
  push:
    tags:
      - "v*"

concurrency: cut-release

permissions:
  contents: write # needed to write releases
  id-token: write # needed for keyless signing
  packages: write # needed for pushing the images to ghcr.io

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # v3
        with:
          go-version: 1.18
          check-latest: true

      - uses: sigstore/cosign-installer@f3c664df7af409cb4873aa5068053ba9d61a57b6 # v2
      - uses: anchore/sbom-action/download-syft@b5042e9d19d8b32849779bfe17673ff84aec702d # v0.11.0
      - uses: imjasonh/setup-ko@78eea08f10db87a7a23a666a4a6fe2734f2eeb8d # v0.4

      - name: Set up Cloud SDK
        uses: google-github-actions/auth@ceee102ec2387dd9e844e01b530ccd4ec87ce955 # v0.8.0
        with:
          workload_identity_provider: 'projects/498091336538/locations/global/workloadIdentityPools/githubactions/providers/sigstore-policy-controller'
          service_account: 'gha-policy-controller@projectsigstore.iam.gserviceaccount.com'

      - name: creds
        run: gcloud auth configure-docker --quiet

      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3

      - uses: goreleaser/goreleaser-action@68acf3b1adf004ac9c2f0a4259e85c5f66e99bef # v3
        with:
          install-only: true

      - name: release
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: copy-signed-release-to-ghcr
        run: make copy-signed-release-to-ghcr || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
